### ISSUE TITLE
standard init throws error

### ISSUE THREAD

**Issue by marcus-at-localhost** [ashergarland/easy-waypoint-animate#1]
```js
$(document).ready(function() {
	InitWaypointAnimations();
});
```
throws: **Uncaught TypeError: Cannot read property 'offset' of undefined**

```js
$(document).ready(function() {
	InitWaypointAnimations({});
});
```
works.

Cheers.

**Comment by ashergarland** [comment]
Fixed: https://github.com/ashergarland/easy-waypoint-animate/commit/7f9383eae30ace78a9a55c5557eadaf35cd6e416

Thank you for reporting the issue!
